/*
 * Artisan - GUI for Laravel developers.
 * Copyright (C) 2017  Mateo Leal.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.mateolegi.Artisan.views;

import io.github.mateolegi.Artisan.controllers.CheckComponent;
import io.github.mateolegi.Artisan.main.Main;
import io.github.mateolegi.Artisan.util.Hash;
import java.beans.PropertyChangeEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.nio.channels.Channels;
import java.nio.channels.FileChannel;
import java.nio.channels.ReadableByteChannel;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;

/**
 *
 * @author Mateo Leal
 */
public class InstallComposerProgress extends javax.swing.JDialog {

    /**
     * Creates new form CreateNewProjectProgress
     *
     * @param owner the {@code Frame} from which the dialog is displayed
     * @param modal specifies whether dialog blocks user input to other
     * top-level windows when shown. If {@code true}, the modality type property
     * is set to {@code DEFAULT_MODALITY_TYPE}, otherwise the dialog is
     * modeless.
     */
    public InstallComposerProgress(java.awt.Frame owner, boolean modal) {
        super(owner, modal);
        this.setIconImage(new javax.swing.ImageIcon(getClass()
                .getResource("/io/github/mateolegi/Artisan/images/Artisan.png"))
                .getImage().getScaledInstance(48, 48, java.awt.Image.SCALE_AREA_AVERAGING));
        initComponents();
        InstallComposer p = new InstallComposer(progressBar, secondLabel);
        p.addPropertyChangeListener((PropertyChangeEvent evt) -> {
            if (evt.getPropertyName().equalsIgnoreCase("state")) {
                if (evt.getNewValue() == SwingWorker.StateValue.DONE) {
                    this.dispose();
                }
            }
        });
        p.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        firstLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Configuring Artisan");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N

        firstLabel.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        firstLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstLabel.setText("Configuring Artisan, this may take a while.");

        secondLabel.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        secondLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondLabel.setText("Please, be pacient");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secondLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstLabel)
                .addGap(13, 13, 13)
                .addComponent(secondLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstLabel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel secondLabel;
    // End of variables declaration//GEN-END:variables
}

class InstallComposer extends SwingWorker<Integer, String> {

    private final JProgressBar progressBar;
    private final JLabel label;

    public InstallComposer(JProgressBar progressBar, JLabel label) {
        this.progressBar = progressBar;
        this.label = label;
    }

    @Override
    protected Integer doInBackground() throws Exception {
        progressBar.setIndeterminate(true);
        String php = CheckComponent.getPHPFile();
        if (php.contains(" ")) {
            php = "\"" + php + "\"";
        }
        label.setText("Checking PHP");
        if (CheckComponent.checkPHP() == CheckComponent.PHP_SUCCESSFUL) {
            label.setText("Checking PHP modules");
            if (CheckComponent.getPHPModules() == CheckComponent.PHP_MODULES_SUCCESSFUL) {
                File composerDirectory = new File(Main.APP_DIRECTORY + "\\composer");
                if (!composerDirectory.isDirectory()) {
                    composerDirectory.delete();
                }
                if (!composerDirectory.mkdir()) {
                    if (!composerDirectory.mkdirs()) {
                        System.err.println("Can't create folder");
                    }
                }
                label.setText("Generating Composer installer batch file");
//                try (ReadableByteChannel in = Channels.newChannel(new URL("https://composer.github.io/installer.sig").openStream());
//                        FileChannel out = new FileOutputStream(Main.APP_DIRECTORY + "\\composer\\installer.sig").getChannel()) {
//                    out.transferFrom(in, 0, Long.MAX_VALUE);
                    File signature = new File(new URL("https://composer.github.io/installer.sig").toURI());
                    Process downloadInstallerProcess = Runtime.getRuntime().exec("php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"", null, composerDirectory);
                    downloadInstallerProcess.waitFor();
                    File installer = new File(composerDirectory.getAbsoluteFile() + "\\composer-setup.php");
                    String expectedHash = Hash.getHash(installer);
                    
                    
//                }
                String script
                        = "@echo off\n"
                        + "set COMPOSER_HOME=Home\n"
                        + "if not exist %COMPOSER_HOME% md \"%COMPOSER_HOME%\"\n"
                        + "echo Downloading Composer installer, please wait...\n"
                        + php + " -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"\n"
                        + "echo Checking download\n"
                        + php + " -r \"if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;\"\n"
                        + php + " composer-setup.php\n"
                        + php + " -r \"unlink('composer-setup.php');\"\n"
                        + "call " + php + " composer.phar --version | findstr /i /r /c:\"Composer......version\"\n"
                        + "call " + php + " composer.phar --quiet config --global process-timeout 3000\n"
                        + "set COMPOSER_LOCAL=Local\n"
                        + "if not exist %COMPOSER_LOCAL% md \"%COMPOSER_LOCAL%\"\n"
                        + "call composer --quiet config --global cache-dir \"%COMPOSER_LOCAL%\"\n"
                        + "set COMPOSER_BAT=composer.bat\n"
                        + "if not exist \"%COMPOSER_BAT\" (\n"
                        + "	echo @ECHO OFF> \"%COMPOSER_BAT%\"\n"
                        + "	echo SET COMPOSER_HOME=%%Home>> \"%COMPOSER_BAT%\"\n"
                        + "	echo if not exist %%COMPOSER_HOME%% md \"%%COMPOSER_HOME%%\">> \"%COMPOSER_BAT%\"\n"
                        + "	echo " + php + " \"%%~dp0composer.phar\" %%*>> \"%COMPOSER_BAT%\"\n"
                        + "	echo EXIT /B %%ERRORLEVEL%%>> \"%COMPOSER_BAT%\"\n"
                        + ")\n"
                        + "exit";
                BufferedWriter bw = null;
                try {
                    bw = new BufferedWriter(new FileWriter(new File(Main.APP_DIRECTORY + "\\Composer\\installcomposer.bat")));
                    bw.write(script);
                } catch (IOException e) {
                    System.err.println("Error: " + e.getMessage());
                } finally {
                    try {
                        if (bw != null) {
                            bw.close();
                        }
                    } catch (IOException e) {
                        System.err.println("Error: " + e.getMessage());
                    }
                }
                label.setText("Installing Composer");
                try {
                    Process p = Runtime.getRuntime().exec("cmd.exe /c start " + Main.APP_DIRECTORY + "\\Composer\\installcomposer.bat", null, composerDirectory);
                    p.waitFor();
                    Thread.sleep(60000);
                    label.setText("Intalling Laravel");
                    p = Runtime.getRuntime().exec("composer.bat global require \"laravel/installer\"", null, composerDirectory);
                } catch (InterruptedException | IOException e) {
                    System.err.println("Error: " + e.getMessage());
                }
            }
        }
        progressBar.setIndeterminate(false);
        return 0;
    }
}
