/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.mateolegi.Artisan.views;

import io.github.mateolegi.Artisan.models.Project;
import io.github.mateolegi.Artisan.util.Notification;
import java.awt.AWTException;
import java.io.File;
import java.net.MalformedURLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author mateo.leal
 */
public class NewProjectPanel extends javax.swing.JPanel {

    Notification noti = new Notification();
    
    /**
     * Creates new form NewProjectPanel
     */
    public NewProjectPanel() {
        initComponents();
        existingButton.setOpaque(true);
        existingButton.setBorderPainted(true);
        existingButton.setBackground(new java.awt.Color(149, 165, 166));
        createButton.setOpaque(true);
        createButton.setBorderPainted(true);
        createButton.setBackground(new java.awt.Color(149, 165, 166));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        backButton = new javax.swing.JButton();
        createLabel = new javax.swing.JLabel();
        existingLabel = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        existingButton = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();

        fileChooser.setCurrentDirectory(new java.io.File("C:/Users/" + System.getenv().get("USERNAME")));
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(710, 580));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/mateolegi/Artisan/images/back.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setContentAreaFilled(false);
        backButton.setFocusable(false);
        backButton.setPreferredSize(new java.awt.Dimension(30, 30));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        createLabel.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        createLabel.setText("Create a new Laravel project");

        existingLabel.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        existingLabel.setText("Add an existing project on your computer");

        createButton.setBackground(new java.awt.Color(149, 165, 166));
        createButton.setText("New project");
        createButton.setBorder(null);
        createButton.setContentAreaFilled(false);
        createButton.setFocusable(false);
        createButton.setPreferredSize(new java.awt.Dimension(91, 30));
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createButtonMouseExited(evt);
            }
        });
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        existingButton.setBackground(new java.awt.Color(149, 165, 166));
        existingButton.setText("Existing project");
        existingButton.setBorder(null);
        existingButton.setContentAreaFilled(false);
        existingButton.setFocusable(false);
        existingButton.setPreferredSize(new java.awt.Dimension(91, 30));
        existingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                existingButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                existingButtonMouseExited(evt);
            }
        });
        existingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingButtonActionPerformed(evt);
            }
        });

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(createLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)))
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(existingLabel)
                    .addComponent(existingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(createLabel)
                        .addGap(18, 18, 18)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(existingLabel)
                        .addGap(18, 18, 18)
                        .addComponent(existingButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainWindow topFrame = (MainWindow) (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getProjects();
        topFrame.leftPanel.show();
        topFrame.panelCanvas.add(topFrame.leftPanel);
        topFrame.projectName.setSelected(false);
        topFrame.projectName.setBorderPainted(false);
        topFrame.projectName.setOpaque(false);
        topFrame.manager.getTabbedPane().remove(topFrame.manager.getTabbedPane().indexOfTab("New project"));
    }//GEN-LAST:event_backButtonActionPerformed

    private void createButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseEntered
        createButton.setOpaque(true);
        createButton.setBorderPainted(true);
        createButton.setBackground(new java.awt.Color(189, 195, 199));
    }//GEN-LAST:event_createButtonMouseEntered

    private void createButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseExited
        createButton.setOpaque(true);
        createButton.setBorderPainted(true);
        createButton.setBackground(new java.awt.Color(149, 165, 166));
    }//GEN-LAST:event_createButtonMouseExited

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        fileChooser.showSaveDialog(this);
        MainWindow topFrame = (MainWindow) (JFrame) SwingUtilities.getWindowAncestor(this);
        System.out.println(topFrame);
        if (fileChooser.getSelectedFile() != null) {
            String projectName = JOptionPane.showInputDialog(null, "Project name", "Create project", -1);
            if (projectName != null && !"".equals(projectName) && projectName.trim().length() != 0) {
                CreateNewProjectProgress dialog = new CreateNewProjectProgress(topFrame, true, fileChooser.getSelectedFile(), projectName.replaceAll("\\s", ""));
                dialog.setLocationRelativeTo(topFrame);
                //topFrame.add(dialog);
                dialog.setVisible(true);
                if (new Project(projectName, fileChooser.getSelectedFile().getAbsolutePath() + '\\' + projectName.replaceAll("\\s", "")).save()) {
                    try {
                        noti.displayTray("Project added", "INFO");
                    } catch (AWTException | MalformedURLException ex) {
                        System.out.println("Error: " + ex.getMessage());
                    }
                    LeftPanel leftPanel = new LeftPanel();
                    leftPanel.show();
                    topFrame.getProjects();
                    topFrame.projectName.setText("  " + projectName);
                    topFrame.panelCanvas.add(leftPanel);
                    topFrame.projectsPanel.loadProjects();
                    topFrame.manager.getTabbedPane().remove(topFrame.manager.getTabbedPane().indexOfTab("New project"));
                } else {
                    try {
                        noti.displayTray("Error adding project", "ERROR");
                    } catch (AWTException | MalformedURLException ex) {
                        System.out.println("Error: " + ex.getMessage());
                    }
                }
            }

            fileChooser.setSelectedFile(null);
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void existingButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existingButtonMouseEntered
        existingButton.setOpaque(true);
        existingButton.setBorderPainted(true);
        existingButton.setBackground(new java.awt.Color(189, 195, 199));
    }//GEN-LAST:event_existingButtonMouseEntered

    private void existingButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existingButtonMouseExited
        existingButton.setOpaque(true);
        existingButton.setBorderPainted(true);
        existingButton.setBackground(new java.awt.Color(149, 165, 166));
    }//GEN-LAST:event_existingButtonMouseExited

    private void existingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingButtonActionPerformed
        fileChooser.showOpenDialog(this);
        MainWindow topFrame = (MainWindow) (JFrame) SwingUtilities.getWindowAncestor(this);
        System.out.println(topFrame);
        if (fileChooser.getSelectedFile() != null) {
            File file = new File(fileChooser.getSelectedFile() + "\\artisan");
            if (file.exists() && !file.isDirectory()) {
                String projectName = JOptionPane.showInputDialog(null, "Project name", "Add project", -1);
                if (projectName != null && !"".equals(projectName) && projectName.trim().length() != 0) {
                    Project project = new Project(projectName, fileChooser.getSelectedFile().getAbsolutePath());
                    if (project.save()) {
                        try {
                            noti.displayTray("Project added", "INFO");
                        } catch (AWTException | MalformedURLException ex) {
                            System.out.println("Error: " + ex.getMessage());
                        }
                        LeftPanel leftPanel = new LeftPanel();
                        leftPanel.show();
                        topFrame.getProjects();
                        topFrame.projectName.setText("  " + projectName);
                        topFrame.projectsPanel.loadProjects();
                        topFrame.manager.getTabbedPane().remove(topFrame.manager.getTabbedPane().indexOfTab("New project"));
                    } else {
                        try {
                            noti.displayTray("Error adding project", "ERROR");
                        } catch (AWTException | MalformedURLException ex) {
                            System.out.println("Error: " + ex.getMessage());
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Folder is not a suitable Laravel project", "Artisan not found", JOptionPane.WARNING_MESSAGE);
            }
            fileChooser.setSelectedFile(null);
        }
    }//GEN-LAST:event_existingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel createLabel;
    private javax.swing.JButton existingButton;
    private javax.swing.JLabel existingLabel;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
